/**
 * GENERATED by scripts/gen-schema-version.mjs. Do not edit; run npm run gen:schema.
 *
 * The shape of the database this build of the apps was written against.
 * Provisioning writes the same value onto the settings row when it finishes;
 * when the row says something else, the database is behind and the apps say
 * so. See scripts/schema-fingerprint.mjs.
 */
export const SCHEMA_VERSION = '32fb8672d3b8';
