// Declarative schema for SNPOS. Consumed by provision.mjs.
// Types: s(size) string, i integer, f float, b boolean, d datetime, e(...) enum
// Suffix ! = required, [] = array. Money fields are integers in minor units.

export const DB_ID = process.env.DB_ID || 'snpos';

export const TEAMS = [
  { id: 'cooks', name: 'Cooks' },
  { id: 'waiters', name: 'Waiters' },
  { id: 'cashiers', name: 'Cashiers' },
  { id: 'managers', name: 'Managers' },
  { id: 'admins', name: 'Admins' },
];

export const BUCKETS = [
  {
    id: 'menu-images',
    name: 'Menu images',
    maxSize: 10 * 1024 * 1024,
    extensions: ['jpg', 'jpeg', 'png', 'webp', 'avif'],
    read: ['any'],
    write: ['team:managers', 'team:admins'],
  },
  {
    id: 'branding',
    name: 'Branding',
    maxSize: 5 * 1024 * 1024,
    extensions: ['jpg', 'jpeg', 'png', 'webp', 'svg', 'ico'],
    read: ['any'],
    write: ['team:admins'],
  },
  {
    id: 'receipts',
    name: 'Expense receipts',
    maxSize: 10 * 1024 * 1024,
    extensions: ['jpg', 'jpeg', 'png', 'webp', 'pdf'],
    read: ['team:managers', 'team:admins'],
    write: ['team:cashiers', 'team:managers', 'team:admins'],
  },
];

const ALL_STAFF = ['team:cooks', 'team:waiters', 'team:cashiers', 'team:managers', 'team:admins'];
const MGMT = ['team:managers', 'team:admins'];
const ADMIN = ['team:admins'];

/**
 * perms.read / .create / .update / .delete — arrays of Appwrite role strings.
 * An empty create/update array means: functions only (server API key).
 */
export const COLLECTIONS = [
  // ---------------------------------------------------------------- settings
  {
    id: 'settings',
    name: 'Settings',
    perms: { read: ['any'], create: [], update: ADMIN, delete: [] },
    attributes: [
      ['restaurant_name', 's', 120, true],
      ['timezone', 's', 64, true, 'Africa/Accra'],
      ['currency_code', 's', 3, true, 'GHS'],
      ['currency_symbol', 's', 8, true, 'GH₵'],
      ['currency_decimals', 'i', null, true, 2],
      ['symbol_position', 'e', ['before', 'after'], true, 'before'],
      ['primary_color', 's', 9, true, '#0F766E'],
      ['secondary_color', 's', 9, true, '#F59E0B'],
      ['accent_color', 's', 9, false],
      ['logo_light_id', 's', 64, false],
      ['logo_dark_id', 's', 64, false],
      ['favicon_id', 's', 64, false],
      ['tax_rate_bp', 'i', null, true, 0],
      ['tax_inclusive', 'b', null, true, true],
      ['service_charge_bp', 'i', null, true, 0],
      ['shift_float_policy', 'e', ['zero', 'carry_over', 'prompt'], true, 'zero'],
      ['shift_float_default', 'i', null, true, 0],
      ['kitchen_ack_sla_seconds', 'i', null, true, 60],
      ['kitchen_ping_max_level', 'i', null, true, 4],
      ['require_reject_reason', 'b', null, true, true],
      ['qr_orders_need_approval', 'b', null, true, false],
      ['order_number_prefix', 's', 8, false, 'ORD'],
      ['low_stock_default_bp', 'i', null, true, 3000],
      ['stock_variance_threshold_bp', 'i', null, true, 1000],
      ['stock_variance_value_floor', 'i', null, true, 2000],
      ['expense_approval_threshold', 'i', null, true, 20000],
      ['cash_variance_tolerance', 'i', null, true, 500],
      ['terminal_idle_lock_seconds', 'i', null, true, 180],
    ],
  },
  {
    id: 'payment_methods',
    name: 'Payment methods',
    perms: { read: ['users'], create: ADMIN, update: ADMIN, delete: ADMIN },
    attributes: [
      ['name', 's', 40, true],
      ['kind', 'e', ['cash', 'card', 'mobile_money', 'voucher', 'on_account'], true],
      ['enabled', 'b', null, true, true],
      ['sort', 'i', null, true, 0],
      ['opens_cash_drawer', 'b', null, true, false],
      ['requires_reference', 'b', null, true, false],
      ['counted_at_close', 'b', null, true, true],
      ['gateway', 'e', ['none', 'paystack', 'stripe'], true, 'none'],
      ['surcharge_bp', 'i', null, true, 0],
    ],
    indexes: [['enabled_sort', 'key', ['enabled', 'sort']]],
  },

  // -------------------------------------------------------------------- menu
  {
    id: 'categories',
    name: 'Categories',
    perms: { read: ['any'], create: MGMT, update: MGMT, delete: MGMT },
    attributes: [
      ['name', 's', 120, true],
      ['description', 's', 500, false],
      ['sort', 'i', null, true, 0],
      ['image_id', 's', 64, false],
      ['active', 'b', null, true, true],
      ['availability', 's', 4000, false],
      ['unavailable_display', 'e', ['grey', 'hide'], true, 'grey'],
      ['station', 'e', ['hot', 'cold', 'bar', 'dessert'], true, 'hot'],
    ],
    indexes: [['active_sort', 'key', ['active', 'sort']]],
  },
  {
    id: 'menu_items',
    name: 'Menu items',
    perms: { read: ['any'], create: MGMT, update: MGMT, delete: MGMT },
    attributes: [
      ['category_id', 's', 64, true],
      ['name', 's', 160, true],
      ['description', 's', 1000, false],
      ['price', 'i', null, true, 0],
      ['image_id', 's', 64, false],
      ['image_focal_x', 'f', null, true, 0.5],
      ['image_focal_y', 'f', null, true, 0.5],
      ['sku', 's', 40, false],
      ['active', 'b', null, true, true],
      ['availability', 's', 4000, false],
      ['sold_out_until', 'd', null, false],
      ['prep_minutes', 'i', null, true, 10],
      ['station', 'e', ['hot', 'cold', 'bar', 'dessert', 'inherit'], true, 'inherit'],
      ['tags', 's[]', 40, false],
      ['sort', 'i', null, true, 0],
      ['track_stock', 'b', null, true, false],
    ],
    indexes: [
      ['category_active', 'key', ['category_id', 'active']],
      ['name_search', 'fulltext', ['name']],
    ],
  },
  {
    id: 'addon_groups',
    name: 'Add-on groups',
    perms: { read: ['any'], create: MGMT, update: MGMT, delete: MGMT },
    attributes: [
      ['name', 's', 120, true],
      ['min_select', 'i', null, true, 0],
      ['max_select', 'i', null, true, 1],
      ['required', 'b', null, true, false],
      ['sort', 'i', null, true, 0],
    ],
  },
  {
    id: 'addon_options',
    name: 'Add-on options',
    perms: { read: ['any'], create: MGMT, update: MGMT, delete: MGMT },
    attributes: [
      ['group_id', 's', 64, true],
      ['name', 's', 120, true],
      ['price_delta', 'i', null, true, 0], // may be negative
      ['active', 'b', null, true, true],
      ['sort', 'i', null, true, 0],
      ['default_selected', 'b', null, true, false],
      ['max_qty', 'i', null, true, 1],
    ],
    indexes: [['group', 'key', ['group_id', 'sort']]],
  },
  {
    id: 'menu_item_addon_groups',
    name: 'Item add-on links',
    perms: { read: ['any'], create: MGMT, update: MGMT, delete: MGMT },
    attributes: [
      ['menu_item_id', 's', 64, true],
      ['group_id', 's', 64, true],
      ['sort', 'i', null, true, 0],
      ['price_delta_override', 'i', null, false],
      ['required_override', 'b', null, false],
    ],
    indexes: [['item', 'key', ['menu_item_id', 'sort']]],
  },

  // ------------------------------------------------------------------- floor
  {
    id: 'tables',
    name: 'Tables',
    perms: { read: ALL_STAFF, create: MGMT, update: ALL_STAFF, delete: MGMT },
    attributes: [
      ['label', 's', 20, true],
      ['zone', 's', 60, false],
      ['seats', 'i', null, true, 4],
      ['qr_token', 's', 64, true],
      ['status', 'e', ['free', 'seated', 'ordered', 'bill_requested', 'dirty'], true, 'free'],
      ['current_order_id', 's', 64, false],
      ['current_session_id', 's', 64, false],
      ['active', 'b', null, true, true],
      ['sort', 'i', null, true, 0],
    ],
    indexes: [['qr_token_unique', 'unique', ['qr_token']], ['zone_sort', 'key', ['zone', 'sort']]],
  },
  {
    id: 'dining_sessions',
    name: 'Dining sessions',
    perms: { read: ALL_STAFF, create: [], update: [], delete: [] },
    attributes: [
      ['table_id', 's', 64, true],
      ['opened_at', 'd', null, true],
      ['closed_at', 'd', null, false],
      ['guest_count', 'i', null, true, 1],
      ['anon_user_ids', 's[]', 64, false],
      ['status', 'e', ['open', 'billing', 'closed'], true, 'open'],
      ['shift_id', 's', 64, false],
    ],
    indexes: [['table_status', 'key', ['table_id', 'status']]],
  },

  // ------------------------------------------------------------------ orders
  {
    id: 'orders',
    name: 'Orders',
    perms: { read: ALL_STAFF, create: [], update: [], delete: [] },
    attributes: [
      ['order_no', 's', 20, true],
      ['idem_key', 's', 64, true],
      ['version', 'i', null, true, 1],
      ['channel', 'e', ['qr', 'waiter', 'counter', 'takeaway', 'delivery'], true],
      ['table_id', 's', 64, false],
      ['session_id', 's', 64, false],
      ['shift_id', 's', 64, true],
      ['status', 'e', ['PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'SERVED', 'CLOSED', 'REJECTED', 'CANCELLED'], true, 'PENDING'],
      ['alert_level', 'i', null, true, 0],
      ['accepted_at', 'd', null, false],
      ['accepted_by', 's', 64, false],
      ['rejected_at', 'd', null, false],
      ['rejected_by', 's', 64, false],
      ['reject_reason_code', 'e', ['out_of_stock', 'too_busy', 'item_unavailable', 'closing_soon', 'duplicate', 'customer_request', 'other'], false],
      ['reject_reason_note', 's', 500, false],
      ['subtotal', 'i', null, true, 0],
      ['discount_total', 'i', null, true, 0],
      ['tax_total', 'i', null, true, 0],
      ['service_total', 'i', null, true, 0],
      ['tip_total', 'i', null, true, 0],
      ['total', 'i', null, true, 0],
      ['currency_code', 's', 3, true],
      ['payment_status', 'e', ['unpaid', 'partial', 'paid', 'refunded'], true, 'unpaid'],
      ['placed_by', 's', 80, true],
      ['guest_count', 'i', null, true, 1],
      ['notes', 's', 500, false],
    ],
    indexes: [
      ['idem_unique', 'unique', ['idem_key']],
      ['order_no_unique', 'unique', ['order_no']],
      ['shift_status', 'key', ['shift_id', 'status']],
      ['status_created', 'key', ['status', '$createdAt']],
      ['session', 'key', ['session_id']],
      ['table', 'key', ['table_id']],
    ],
  },
  {
    id: 'order_items',
    name: 'Order items',
    perms: { read: ALL_STAFF, create: [], update: [], delete: [] },
    attributes: [
      ['order_id', 's', 64, true],
      ['menu_item_id', 's', 64, true],
      ['name_snapshot', 's', 160, true],
      ['unit_price', 'i', null, true, 0],
      ['qty', 'i', null, true, 1],
      ['addons', 's', 2000, false],
      ['line_total', 'i', null, true, 0],
      ['notes', 's', 300, false],
      ['station', 'e', ['hot', 'cold', 'bar', 'dessert'], true, 'hot'],
      ['status', 'e', ['queued', 'preparing', 'ready', 'served', 'void'], true, 'queued'],
      ['void_reason', 's', 300, false],
      ['voided_by', 's', 64, false],
      ['course', 'i', null, true, 1],
      ['seat_no', 'i', null, false],
    ],
    indexes: [['order', 'key', ['order_id']], ['station_status', 'key', ['station', 'status']]],
  },
  {
    id: 'payments',
    name: 'Payments',
    perms: { read: ['team:cashiers', ...MGMT], create: [], update: [], delete: [] },
    attributes: [
      ['order_id', 's', 64, true],
      ['shift_id', 's', 64, true],
      ['method_id', 's', 64, true],
      ['method_kind_snapshot', 's', 20, true],
      ['amount', 'i', null, true, 0],
      ['tip', 'i', null, true, 0],
      ['change_given', 'i', null, true, 0],
      ['reference', 's', 120, false],
      ['status', 'e', ['pending', 'captured', 'failed', 'refunded', 'voided'], true, 'captured'],
      ['gateway_ref', 's', 120, false],
      ['gateway_payload', 's', 4000, false],
      ['taken_by', 's', 64, true],
      ['refund_of', 's', 64, false],
      ['refund_reason', 's', 300, false],
    ],
    indexes: [['order', 'key', ['order_id']], ['shift_status', 'key', ['shift_id', 'status']]],
  },

  // ------------------------------------------------------------------ shifts
  {
    id: 'shifts',
    name: 'Shifts',
    perms: { read: ['team:cashiers', ...MGMT], create: [], update: [], delete: [] },
    attributes: [
      ['code', 's', 40, true],
      ['status', 'e', ['open', 'closing', 'closed', 'reopened'], true, 'open'],
      ['opened_by', 's', 64, true],
      ['opened_at', 'd', null, true],
      ['opening_floats', 's', 2000, true],
      ['float_source', 'e', ['zero', 'manual', 'carried_over'], true, 'zero'],
      ['carried_from_shift_id', 's', 64, false],
      ['carry_approved_by', 's', 64, false],
      ['closed_by', 's', 64, false],
      ['closed_at', 'd', null, false],
      ['expected', 's', 2000, false],
      ['counted', 's', 2000, false],
      ['variance', 's', 2000, false],
      ['variance_note', 's', 1000, false],
      ['sales_total', 'i', null, true, 0],
      ['expense_total', 'i', null, true, 0],
      ['tax_total', 'i', null, true, 0],
      ['tip_total', 'i', null, true, 0],
      ['discount_total', 'i', null, true, 0],
      ['void_total', 'i', null, true, 0],
      ['refund_total', 'i', null, true, 0],
      ['cogs_total', 'i', null, true, 0],
      ['covers', 'i', null, true, 0],
      ['stock_check_status', 'e', ['pending', 'complete'], true, 'pending'],
      ['posted_to_ledger', 'b', null, true, false],
      ['notes', 's', 1000, false],
    ],
    indexes: [['status_opened', 'key', ['status', 'opened_at']], ['code_unique', 'unique', ['code']]],
  },
  {
    id: 'shift_expenses',
    name: 'Shift expenses',
    perms: { read: ['team:cashiers', ...MGMT], create: ['team:cashiers', ...MGMT], update: MGMT, delete: ADMIN },
    attributes: [
      ['shift_id', 's', 64, true],
      ['category', 'e', ['supplies', 'transport', 'utilities', 'repairs', 'staff_advance', 'petty_cash', 'other'], true],
      ['payee', 's', 160, false],
      ['amount', 'i', null, true, 0],
      ['paid_from_method_id', 's', 64, true],
      ['note', 's', 500, false],
      ['receipt_file_id', 's', 64, false],
      ['created_by', 's', 64, true],
      ['approved_by', 's', 64, false],
      ['approval_status', 'e', ['not_required', 'pending', 'approved', 'rejected'], true, 'not_required'],
    ],
    indexes: [['shift', 'key', ['shift_id']]],
  },
  {
    id: 'shift_stock_checks',
    name: 'Shift stock checks',
    perms: { read: ALL_STAFF, create: ['team:cashiers', 'team:cooks', ...MGMT], update: ['team:cashiers', 'team:cooks', ...MGMT], delete: [] },
    attributes: [
      ['shift_id', 's', 64, true],
      ['ingredient_id', 's', 64, true],
      ['opening_qty', 'f', null, true, 0],
      ['theoretical_qty', 'f', null, true, 0],
      ['counted_qty', 'f', null, false],
      ['status', 'e', ['OK', 'LOW', 'OUT'], true, 'OK'],
      ['status_source', 'e', ['auto', 'manual_override'], true, 'auto'],
      ['variance_qty', 'f', null, true, 0],
      ['variance_value', 'i', null, true, 0],
      ['checked_by', 's', 64, false],
      ['note', 's', 300, false],
    ],
    indexes: [['shift_ing', 'key', ['shift_id', 'ingredient_id']]],
  },

  // --------------------------------------------------------------- inventory
  {
    id: 'ingredients',
    name: 'Ingredients',
    perms: { read: ALL_STAFF, create: MGMT, update: MGMT, delete: ADMIN },
    attributes: [
      ['name', 's', 160, true],
      ['unit', 'e', ['g', 'kg', 'ml', 'l', 'each', 'pack'], true],
      ['base_unit_cost', 'i', null, true, 0],
      ['current_qty', 'f', null, true, 0],
      ['par_level', 'f', null, true, 0],
      ['low_threshold', 'f', null, false],
      ['critical', 'b', null, true, false],
      ['supplier_id', 's', 64, false],
      ['category', 's', 80, false],
      ['shelf_life_days', 'i', null, false],
      ['active', 'b', null, true, true],
    ],
    indexes: [['active_name', 'key', ['active', 'name']], ['critical', 'key', ['critical']]],
  },
  {
    id: 'recipes',
    name: 'Recipes',
    perms: { read: ALL_STAFF, create: MGMT, update: MGMT, delete: MGMT },
    attributes: [
      ['menu_item_id', 's', 64, false],
      ['addon_option_id', 's', 64, false],
      ['ingredient_id', 's', 64, true],
      ['qty_per_unit', 'f', null, true, 0],
      ['wastage_bp', 'i', null, true, 0],
    ],
    indexes: [['item', 'key', ['menu_item_id']], ['ingredient', 'key', ['ingredient_id']], ['addon', 'key', ['addon_option_id']]],
  },
  {
    id: 'suppliers',
    name: 'Suppliers',
    perms: { read: ALL_STAFF, create: MGMT, update: MGMT, delete: ADMIN },
    attributes: [
      ['name', 's', 160, true],
      ['contact', 's', 120, false],
      ['phone', 's', 40, false],
      ['email', 's', 160, false],
      ['payment_terms', 's', 80, false],
      ['active', 'b', null, true, true],
    ],
  },
  {
    id: 'purchases',
    name: 'Purchases',
    perms: { read: MGMT, create: MGMT, update: MGMT, delete: ADMIN },
    attributes: [
      ['supplier_id', 's', 64, true],
      ['invoice_no', 's', 80, false],
      ['purchased_at', 'd', null, true],
      ['subtotal', 'i', null, true, 0],
      ['tax', 'i', null, true, 0],
      ['total', 'i', null, true, 0],
      ['paid_from_method_id', 's', 64, false],
      ['shift_id', 's', 64, false],
      ['received_by', 's', 64, true],
      ['document_file_id', 's', 64, false],
    ],
    indexes: [['supplier_date', 'key', ['supplier_id', 'purchased_at']]],
  },
  {
    id: 'purchase_items',
    name: 'Purchase items',
    perms: { read: MGMT, create: MGMT, update: MGMT, delete: ADMIN },
    attributes: [
      ['purchase_id', 's', 64, true],
      ['ingredient_id', 's', 64, true],
      ['qty', 'f', null, true, 0],
      ['unit_cost', 'i', null, true, 0],
      ['line_total', 'i', null, true, 0],
    ],
    indexes: [['purchase', 'key', ['purchase_id']], ['ingredient', 'key', ['ingredient_id']]],
  },
  {
    id: 'stock_movements',
    name: 'Stock movements',
    perms: { read: MGMT, create: [], update: [], delete: [] },
    attributes: [
      ['ingredient_id', 's', 64, true],
      ['type', 'e', ['purchase', 'sale_depletion', 'waste', 'adjustment', 'count_correction', 'transfer'], true],
      ['qty_delta', 'f', null, true, 0],
      ['unit_cost', 'i', null, true, 0],
      ['ref_type', 's', 40, false],
      ['ref_id', 's', 64, false],
      ['shift_id', 's', 64, false],
      ['created_by', 's', 64, false],
      ['note', 's', 300, false],
    ],
    indexes: [['ingredient_created', 'key', ['ingredient_id', '$createdAt']], ['shift', 'key', ['shift_id']]],
  },
  {
    id: 'stock_flags',
    name: 'Stock variance flags',
    perms: { read: MGMT, create: [], update: MGMT, delete: ADMIN },
    attributes: [
      ['ingredient_id', 's', 64, true],
      ['period_start', 'd', null, true],
      ['period_end', 'd', null, true],
      ['theoretical_usage', 'f', null, true, 0],
      ['actual_usage', 'f', null, true, 0],
      ['variance_qty', 'f', null, true, 0],
      ['variance_bp', 'i', null, true, 0],
      ['variance_value', 'i', null, true, 0],
      ['severity', 'e', ['info', 'warn', 'critical'], true, 'warn'],
      ['likely_causes', 's[]', 40, false],
      ['status', 'e', ['open', 'investigating', 'resolved'], true, 'open'],
      ['resolution_note', 's', 1000, false],
      ['resolved_by', 's', 64, false],
    ],
    indexes: [['status_severity', 'key', ['status', 'severity']], ['ingredient', 'key', ['ingredient_id']]],
  },

  // -------------------------------------------------------------- accounting
  {
    id: 'accounts',
    name: 'Chart of accounts',
    perms: { read: MGMT, create: ADMIN, update: ADMIN, delete: ADMIN },
    attributes: [
      ['code', 's', 10, true],
      ['name', 's', 120, true],
      ['type', 'e', ['asset', 'liability', 'equity', 'revenue', 'expense'], true],
      ['parent_code', 's', 10, false],
      ['system', 'b', null, true, false],
    ],
    indexes: [['code_unique', 'unique', ['code']]],
  },
  {
    id: 'journal_entries',
    name: 'Journal entries',
    perms: { read: MGMT, create: [], update: [], delete: [] },
    attributes: [
      ['date', 'd', null, true],
      ['source', 'e', ['shift_close', 'purchase', 'expense', 'refund', 'adjustment', 'reversal'], true],
      ['source_id', 's', 64, false],
      ['shift_id', 's', 64, false],
      ['memo', 's', 500, false],
      ['posted_by', 's', 64, true],
      ['reversed_by', 's', 64, false],
    ],
    indexes: [['date', 'key', ['date']], ['shift', 'key', ['shift_id']]],
  },
  {
    id: 'journal_lines',
    name: 'Journal lines',
    perms: { read: MGMT, create: [], update: [], delete: [] },
    attributes: [
      ['entry_id', 's', 64, true],
      ['account_code', 's', 10, true],
      ['debit', 'i', null, true, 0],
      ['credit', 'i', null, true, 0],
      ['memo', 's', 300, false],
    ],
    indexes: [['entry', 'key', ['entry_id']], ['account', 'key', ['account_code']]],
  },

  // -------------------------------------------------------------- people/ops
  {
    id: 'staff_profiles',
    name: 'Staff profiles',
    perms: { read: ALL_STAFF, create: [], update: [], delete: [] },
    attributes: [
      ['user_id', 's', 64, true],
      ['display_name', 's', 120, true],
      ['role', 'e', ['cook', 'waiter', 'cashier', 'manager', 'admin'], true],
      ['pin_hash', 's', 255, false],
      ['pin_set_at', 'd', null, false],
      ['active', 'b', null, true, true],
      ['phone', 's', 40, false],
      ['hired_at', 'd', null, false],
      ['can_open_shift', 'b', null, true, false],
      ['can_close_shift', 'b', null, true, false],
      ['can_void', 'b', null, true, false],
      ['can_discount_up_to_bp', 'i', null, true, 0],
    ],
    indexes: [['user_unique', 'unique', ['user_id']], ['active_role', 'key', ['active', 'role']]],
  },
  {
    id: 'devices',
    name: 'Devices',
    perms: { read: ALL_STAFF, create: ALL_STAFF, update: ALL_STAFF, delete: MGMT },
    attributes: [
      ['name', 's', 80, true],
      ['kind', 'e', ['kds', 'pos', 'admin'], true],
      ['station', 'e', ['hot', 'cold', 'bar', 'dessert', 'all'], true, 'all'],
      ['last_seen', 'd', null, true],
      ['audio_ok', 'b', null, true, false],
      ['app_version', 's', 40, false],
    ],
    indexes: [['kind_seen', 'key', ['kind', 'last_seen']]],
  },
  {
    id: 'audit_log',
    name: 'Audit log',
    perms: { read: MGMT, create: [], update: [], delete: [] },
    attributes: [
      ['actor_id', 's', 64, true],
      ['actor_role', 's', 20, false],
      ['action', 's', 80, true],
      ['entity_type', 's', 60, false],
      ['entity_id', 's', 64, false],
      ['before', 's', 4000, false],
      ['after', 's', 4000, false],
      ['ip', 's', 60, false],
      ['device', 's', 120, false],
      ['shift_id', 's', 64, false],
    ],
    indexes: [['actor_created', 'key', ['actor_id', '$createdAt']], ['action', 'key', ['action']]],
  },
];

export const SEED_ACCOUNTS = [
  ['1000', 'Cash on hand', 'asset'],
  ['1010', 'Card clearing', 'asset'],
  ['1020', 'Mobile money clearing', 'asset'],
  ['1200', 'Inventory', 'asset'],
  ['2100', 'Tax payable', 'liability'],
  ['2200', 'Tips payable', 'liability'],
  ['2300', 'Accounts payable', 'liability'],
  ['3000', 'Owner equity', 'equity'],
  ['4000', 'Food sales', 'revenue'],
  ['4010', 'Beverage sales', 'revenue'],
  ['4900', 'Discounts given', 'revenue'],
  ['5000', 'Cost of goods sold', 'expense'],
  ['6000', 'Supplies', 'expense'],
  ['6010', 'Transport', 'expense'],
  ['6020', 'Utilities', 'expense'],
  ['6030', 'Repairs & maintenance', 'expense'],
  ['6040', 'Staff advances', 'expense'],
  ['6050', 'Petty cash', 'expense'],
  ['6090', 'Other expenses', 'expense'],
  ['7000', 'Cash over / short', 'expense'],
];

export const SEED_PAYMENT_METHODS = [
  { name: 'Cash', kind: 'cash', sort: 1, opens_cash_drawer: true, counted_at_close: true },
  { name: 'Card', kind: 'card', sort: 2, requires_reference: true, counted_at_close: true },
];
